version: '3.9'
services:
  app:
    build: .
    image: share_post:1.0.0
    command: /bin/sh -c "rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    depends_on:
      - mysql
      - redis
      - sidekiq
    links:
      - mysql
    ports:
      - '3000:3000'
      - '1234:1234'
      - '26162:26162'
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./containers/mysql:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '4306:3306'
  redis:
    image: redis:7.0
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - 6379:6379
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - mysql
      - redis
    links:
      - mysql
volumes:
  bundle:
  mysql:
  redis:
