default: &default
  adapter: mysql2
  encoding: utf8mb4
  charaset: utf8mb4
  host: <%= DbConfig.database_host %>
  username: <%= DbConfig.database_user %>
  password: <%= DbConfig.database_password %>
  database: <%= DbConfig.database_name %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default